version: '3'
services:
  tracker1:
    container_name: tracker1
    image: luhuiguo/fastdfs
    command: tracker
    network_mode: host
    environment:
      - PORT=2222   
    volumes:
      - /opt/fdfs/conf/tracker1:/etc/fdfs      
      - /var/fdfs/tracker1:/var/fdfs    
  storage1:
    container_name: storage1
    image: luhuiguo/fastdfs
    command: storage
    network_mode: host  
    environment:
      - TRACKER_SERVER=10.1.53.102:2222
      - GROUP_NAME=test
    volumes:
      - /opt/fdfs/conf/storage1:/etc/fdfs  
      - /var/fdfs/storage1:/var/fdfs  
  storage2:
    container_name: storage2
    image: luhuiguo/fastdfs
    command: storage
    network_mode: host  
    environment:
      - PORT=3333 
      - TRACKER_SERVER=10.1.53.102:2222
      - GROUP_NAME=test
    volumes:
      - /opt/fdfs/conf/storage2:/etc/fdfs  
      - /var/fdfs/storage2:/var/fdfs
                    