version: '3'
services:
  tracker:
    container_name: tracker
    image: luhuiguo/fastdfs
    # ports:
    #   - 22122:22122
    #   - 8080:8080
    volumes:
      - /var/fdfs/tracker:/var/fdfs
    network_mode: host   
  storage:
    container_name: storage
    image: luhuiguo/fastdfs
    depends_on:
      - tracker
    network_mode: host
    environment:
      - TRACKER_SERVER=218.244.146.47:22122
    # ports:
    #   - 23000:23000
    #   - 8888:8888
    volumes:
      - /var/fdfs/storage:/var/fdfs        